### ISSUE TITLE
Unsure...

### ISSUE THREAD

**Issue by Ddupasquier** [learn-co-curriculum/phase-4-authorizing-requests-readme#2]
If we're building out an example in one lesson, can't we just continue building on the same example in the next? "Let's say we have a Document Controller" is not clear at all. Do I need to have a Document controller in whatever I'm building? Is this code something I can put inside of an already existing controller so I don't have a million pointless controllers in my app?
These lessons are already hard enough to follow. So maybe, for once, there can be some consistency so I can at least draw some straight lines in my brain.
It's annoying enough that I'm paying like 16k+ yet half this stuff is just copied and pasted from Google.
Please at least make sure it's understandable by novices who have never even fathomed setting up authorization and authentication rather than being as vague as humanly possible.

**Comment by AlveeM** [comment]
Hi @Ddupasquier, thanks for submitting this issue. 

We've designed our section labs as atomic units for the following reasons:

- To make it easier for students to focus on the topic being explained currently.
- Give them the experience of understanding code in different contexts, especially in environments which they didn't create from scratch.
- Software engineers are assigned issues which they have to solve without knowing how every single part fits in. The self contained labs allow students to practice parsing code using the general patterns and principles they've learned. 

We've also provided video walkthroughs to reinforce and expand on the concepts covered in the labs. Furthermore, we always encourage students to reach out to their instructors if they are having difficulty understanding certain topics or how the pieces fit together. 

Since your issue is with the design of the curriculum, we can't make a few changes to this repo to fix the issues you've brought up. We'll take your suggestions into account when we're updating this phase and make changes as required. I'll be closing this issue but if you have any other suggestions, please feel free to submit a new issue.

Thanks again for sharing your suggestions and helping us improve the curriculum.
